spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://10.8.12.76:3306/crm?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useAffectedRows=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  #jpa相关配置
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true


server:
  port: 30001